=== BNHM/biocode/web/bioValidator.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="Validate">
<xs:complexType>
<xs:sequence>

	<xs:element name="Metadata" minOccurs="0">
  	</xs:element>

	<xs:element name="Specimens" type="ruleSet">
  	</xs:element>

	<xs:element name="Collecting_Events" type="ruleSet">
  	</xs:element>

</xs:sequence>
</xs:complexType>
</xs:element>

<!-- ******************************** 
 		Custom definitions 
		The format for the ruleSet 
     ******************************** -->
<xs:complexType name="ruleSet">
   	<xs:sequence>
	<!-- rule definitions -->
  	<xs:element name="rule" maxOccurs="unbounded">
   	<xs:complexType>
	<!-- field is the generic data holder for most rules -->
   		<xs:sequence>
			<xs:element name="field" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
   		</xs:sequence>
		<!-- Rule Type defines the function to be called for validation -->
		<xs:attribute name="type" type="xs:string" use="required"/>
		<xs:attribute name="name" type="xs:string"/>
		<xs:attribute name="plateName" type="xs:string"/>
		<xs:attribute name="wellNumber" type="xs:string"/>
		<xs:attribute name="decimalLatitude" type="xs:string"/>
		<xs:attribute name="decimalLongitude" type="xs:string"/>
		<xs:attribute name="maxErrorInMeters" type="xs:string"/>
		<xs:attribute name="horizontalDatum" type="xs:string"/>
	        <xs:attribute name="level" type="SetLevels" use="required"/>
   	</xs:complexType>
  	</xs:element>

 	</xs:sequence>
	<!-- What form is this data in? See enumeration for supported types -->
	<xs:attribute name="type" type="SetTypes" use="required"/>
</xs:complexType>

<!-- Types of Set Data that we can parse -->
<xs:simpleType name="SetTypes">
	<xs:restriction base="xs:string">
		<!-- An Excel Worksheet, currently in development in bioValidator -->
   		<xs:enumeration value="Worksheet"/>
		<!-- A Tab delimited data file, not yet developed -->
    	        <xs:enumeration value="Tab"/>
  	</xs:restriction>
</xs:simpleType>
<!-- Message Level to display, warning or error -->
<xs:simpleType name="SetLevels">
	<xs:restriction base="xs:string">
   		<xs:enumeration value="error"/>
    	        <xs:enumeration value="warning"/>
  	</xs:restriction>
</xs:simpleType>

</xs:schema>

=== BNHM/biocode/web/biocodeValidator.xml
<?xml version="1.0" encoding="UTF-8"?>
<Validate xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="bioValidator.xsd">

<Metadata>
	<metadata name="loginNames">
      <field>John Deck</field>
      <field>BSCIT Staff</field>
      <field>foo</field>
	</metadata>
</Metadata>

<Specimens type="Worksheet">
    <rule type="checkInXMLFields" name="EnteredBy" level="warning">
      <field>Abigail Poray</field>
      <field>Adrien Derval</field>
      <field>Aimee Ellison</field>
      <field>Alexandre Kaulfuss</field>
      <field>Alice Alldredge</field>
      <field>Allen Collins</field>
      <field>Amaru Heitini</field>
      <field>Amy Driskell</field>
      <field>Anania Tangihia</field>
      <field>Andrea Crowther</field>
      <field>Anne Duplouy</field>
      <field>Antoine N'Yeurt</field>
      <field>Antoine Nancy</field>
      <field>Antony Tepau Tiihiva</field>
      <field>April Yang</field>
      <field>Arapari Tamatea</field>
      <field>Ariihau Durietz</field>
      <field>Ariimoeana Maopi</field>
      <field>Armand Allegri</field>
      <field>Arthur Anker</field>
      <field>Aurelia Juncqua</field>
      <field>Benjamin Ciotti</field>
      <field>Benoit Espiau</field>
      <field>Bernadette Holthuis</field>
      <field>Blais Ah-Sam</field>
      <field>Bradley Balukjian</field>
      <field>Brandon Endo</field>
      <field>BSCIT Staff</field>
      <field>Caitlin Morrison</field>
      <field>Candy Teriinohorai</field>
      <field>Carolyn Kobervig</field>
      <field>Cecile Gaspar</field>
      <field>Cecile Gaspard</field>
      <field>Charles Lydeard</field>
      <field>Chris Ahlgren</field>
      <field>Chris Meyer</field>
      <field>Claire Etienne</field>
      <field>Claude Payri</field>
      <field>Cohina Murphy</field>
      <field>Coralie Vermenot</field>
      <field>Cory Pittman</field>
      <field>Craig Moritz</field>
      <field>Curtis Ewing</field>
      <field>Curtis Ewing and Andrew Brennan</field>
      <field>Curtis P. Ewing</field>
      <field>Dan Polhemus</field>
      <field>Danielle Desmet</field>
      <field>David G. Smith</field>
      <field>David Hembry</field>
      <field>David Lecchini</field>
      <field>David Liitschweiger</field>
      <field>David Reed</field>
      <field>David Touitou</field>
      <field>Derek Cox</field>
      <field>Diana M. Percy</field>
      <field>Dominique Ponton</field>
      <field>Edward Braun</field>
      <field>Elin Claridge</field>
      <field>Ellarae Miner</field>
      <field>Elodie Vogel</field>
      <field>Emily Hornett</field>
      <field>Emmanuel Roberts</field>
      <field>Enoha Riveta</field>
      <field>Eric Clua</field>
      <field>Erica Spotswood</field>
      <field>Fenuaura Richmond</field>
      <field>Filane Aroquiame</field>
      <field>Flaminia Tepau Tiihiva</field>
      <field>Franck Lerouvreur</field>
      <field>Frank Murphy</field>
      <field>Fred Jacq</field>
      <field>Genelle Harrison</field>
      <field>George Hecht</field>
      <field>George K. Roderick</field>
      <field>George Roderick</field>
      <field>Germain Raitini</field>
      <field>Gina McGuire</field>
      <field>GK-12 April 3 2009 Field Trip</field>
      <field>Grand Pittman Natura</field>
      <field>Gustav Paulay</field>
      <field>Hannah Stewart</field>
      <field>Harry Palm</field>
      <field>Hawaiki Teriinohorai</field>
      <field>Heia Teraiharoa</field>
      <field>Herenui Mahuta</field>
      <field>Hinanui Fournier</field>
      <field>Hivanui Maiarii</field>
      <field>Homai Howel-Tonohiti</field>
      <field>Huna Homai</field>
      <field>Hunter Lenihan</field>
      <field>Ioane McIlroy</field>
      <field>Ipeva Gitton</field>
      <field>J.T. Boehm</field>
      <field>Jada Simon White</field>
      <field>James Liebherr</field>
      <field>James Russell</field>
      <field>James Thomas</field>
      <field>Jean Letournaux</field>
      <field>Jean Letourneux</field>
      <field>Jean-Francois Butaud</field>
      <field>Jean-Louis Menou</field>
      <field>Jeffrey Hunt</field>
      <field>Jeffrey T. Williams</field>
      <field>Jenna Moore</field>
      <field>Jerome Petit</field>
      <field>Jimmy Mornet</field>
      <field>Jimmy O'Donnell</field>
      <field>Joe C. Spagna</field>
      <field>Joel Nitta</field>
      <field>John Deck</field>
      <field>John Houder</field>
      <field>Jon Norenburg</field>
      <field>Jonathan Delalande</field>
      <field>Jonathan Geller</field>
      <field>Joseph Poupin</field>
      <field>Josua Tuahiva</field>
      <field>Jules-Marin Lejeune</field>
      <field>Julie Grandgirard</field>
      <field>Julien Grignon</field>
      <field>Kahaia Faatauira</field>
      <field>Kate Hanson</field>
      <field>Katie Hendrickson</field>
      <field>Kealoha Teriitahi</field>
      <field>Keani Lo</field>
      <field>Kelly Maro</field>
      <field>Keshi Fuller</field>
      <field>Kristine White</field>
      <field>La Vonne Englund</field>
      <field>Lainie Moreux</field>
      <field>Laiza Teharuru</field>
      <field>Lee Weigt</field>
      <field>Leilanie Pangier</field>
      <field>Les Watling</field>
      <field>Lindsey Tribondeau</field>
      <field>Livia Tetiarahi</field>
      <field>Local Fishermen</field>
      <field>Louison</field>
      <field>Loulin Otime</field>
      <field>Lucie Billon</field>
      <field>Lucie Faulquier</field>
      <field>Lydia Baker</field>
      <field>Lydiane Mattio</field>
      <field>Maeva Besson</field>
      <field>Mahinui Russel</field>
      <field>Maire Pean</field>
      <field>Malu Yoshida</field>
      <field>Mandy Bemis</field>
      <field>Manea Selig</field>
      <field>Manutea Couterel</field>
      <field>Marama Persin</field>
      <field>Margarita Hadjistylli</field>
      <field>Margotte Genoud</field>
      <field>Maria Tonione</field>
      <field>Marie Fourdrigniez</field>
      <field>Marjorie Saillan</field>
      <field>Marta deMaintenon</field>
      <field>Maruatea Fanaurai</field>
      <field>Mathilde Williams</field>
      <field>Matohi Pitoura</field>
      <field>Matt McElroy</field>
      <field>Matteo Garbelotto</field>
      <field>Matthias Vignon</field>
      <field>Matthieu Leray</field>
      <field>Maxime Beraud</field>
      <field>Maxime Galerne</field>
      <field>Maya deVries</field>
      <field>Meaghan Parker</field>
      <field>Megan Wallis</field>
      <field>Melissa Nadin</field>
      <field>Melissa Prybis</field>
      <field>Melissa Spitler</field>
      <field>Menelaos Stavrinides</field>
      <field>Michel Maihi</field>
      <field>Michel Veuille</field>
      <field>Mihiarii Lowgreen</field>
      <field>Milada Tehono</field>
      <field>Mirabelle Raparii</field>
      <field>Moemoe Vahirua</field>
      <field>Molly Wright</field>
      <field>Natalie Mary</field>
      <field>Natalie Reeder</field>
      <field>Nathalie Mary</field>
      <field>Nathalie Uhl</field>
      <field>Neil Davies</field>
      <field>Nicholas Fletcher</field>
      <field>Nicolas Buray</field>
      <field>Nicole Gravier-Bonnet</field>
      <field>Oris Sanjur</field>
      <field>Pascal Titifa</field>
      <field>Pascal Ung</field>
      <field>Patrick Plantard</field>
      <field>Peter T. Oboyski</field>
      <field>Phil Bock</field>
      <field>Philippe Bacchet</field>
      <field>Philippe Bachet</field>
      <field>Phillippe Bacchet</field>
      <field>Pierre Sasal</field>
      <field>Pierre-Yves Cousteau</field>
      <field>Punua Terooatea</field>
      <field>Rahiti Hunter</field>
      <field>Raianu Estebe</field>
      <field>Raimana Teuraurii</field>
      <field>Rainui Teriinohorai</field>
      <field>Rauhotu Autai</field>
      <field>Rautea Vongue</field>
      <field>Rautere Teharuru</field>
      <field>Ravahere Nehemia</field>
      <field>Rene Galzin</field>
      <field>Reo Terai</field>
      <field>Rick Hochberg</field>
      <field>Rico Haring</field>
      <field>Rob Adlard</field>
      <field>Robby Teuira</field>
      <field>Robert Adland</field>
      <field>Robert Fisher</field>
      <field>Rod Bray</field>
      <field>Rodney Bray</field>
      <field>Rogo Agnie</field>
      <field>Romain Causse</field>
      <field>Ronald Englund</field>
      <field>Ronan Dieutegard</field>
      <field>Rosemary Gillespie</field>
      <field>Roxane Lievens</field>
      <field>Roy Caldwell</field>
      <field>Rudy Horoi</field>
      <field>S. Geange</field>
      <field>Sarah Bergemann</field>
      <field>Sarah McPherson</field>
      <field>Scott Fay</field>
      <field>Seabird McKeon</field>
      <field>Serge Planes</field>
      <field>Shane W Geange</field>
      <field>Shane W. Geange</field>
      <field>Shannon Kanakaole</field>
      <field>Sharein El-Tourky</field>
      <field>Shelby E. Boyer</field>
      <field>Sienna Witthans</field>
      <field>Soad</field>
      <field>Stephanie Bush</field>
      <field>Stephanie Juncqua</field>
      <field>Steve Haddock</field>
      <field>Steve Stones-Havas</field>
      <field>Suzanne Vinette</field>
      <field>Sylvain Charlat</field>
      <field>Tamatea Denarie</field>
      <field>Tapunui Adams</field>
      <field>Tautua Tapotofarerani</field>
      <field>Tehaamoana You-Sing</field>
      <field>Tehehea Tapotofarerani</field>
      <field>Tehere Nehemia</field>
      <field>Tehine Tavi</field>
      <field>Temanu Teihotu</field>
      <field>Temauri Vaimeho</field>
      <field>Tepoea Taata</field>
      <field>Tereroa Tereitua</field>
      <field>Teretini Teihotaata</field>
      <field>Terika Gillot</field>
      <field>Tevero Purotu</field>
      <field>Thibault Ramage</field>
      <field>Thomas Cribb</field>
      <field>Tiare Brenda</field>
      <field>Tiarii Papara</field>
      <field>Tikanui Smith</field>
      <field>Timeri Thieme</field>
      <field>Tipari Haumani</field>
